name: webapp-build

# branch condition
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    # specify the env which we have to use from github repo
    environment: webapp-build-env-vars

    # consume secrets
    env:
      MYSQL_USER: ${{ SECRETS.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      TEST_MYSQL_DATABASE: ${{ secrets.TEST_MYSQL_DATABASE }}
    
    # Steps to run the build
    steps:
    - uses: actions/checkout@v4.2.1
    
    # Setup python 
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.12'
     
    # Install python dependencies 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Debug Environment Variables
      run: |
        echo "MYSQL_USER: $MYSQL_USER"
        echo "MYSQL_HOST: $MYSQL_HOST"
        echo "MYSQL_PORT: $MYSQL_PORT"
        echo "TEST_MYSQL_DATABASE: $TEST_MYSQL_DATABASE"
    
    # Run unit test cases for the webapp
    - name: Run tests
      run: pytest -v -s ./tests/test_app.py