name: webapp-build

# branch condition
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    # consume secrets
    env:
      TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    
    # Steps to run the build
    steps:
    - uses: actions/checkout@v4.2.1
    
    # Setup python 
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.12'
     
    # Install python dependencies 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
     
    # Run unit test cases for the webapp
    - name: Run tests
      run: pytest ./tests/test_app.py